version: '3.8'

services:
  frontend:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile
    ports:
      - "80:80"
  
  backend:
    build:
      context: ${BACKEND_PATH}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  microservice:
    build:
      context: ${MICROSERVICE_PATH}
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
