version: '3.8'

services:
  frontend:
    build:
      context: ${FRONTEND_PATH}
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  backend:
    build:
      context: ${BACKEND_PATH}
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - ${BACKEND_PATH}/config/.env
  
  microservice:
    build:
      context: ${MICROSERVICE_PATH}
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
